version: '3'

services:
  # ndakisa-api:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: ndakisa-api
  #   image: ndakisa-api
  #   restart: unless-stopped
  #   ports:
  #     - "3002:3002"
  #   expose:
  #     - 3002
  #   networks:
  #     - app-network-ndakisa
  #   volumes:
  #     - ./ndakisa-api/:/app
  #     - /app/node_modules
  #   depends_on:
  #     - db
  #   env_file:
  #     - .env

  db:
    restart: always
    image: postgres:15
    container_name: ndakisa_db
    command: ["-c", "shared_buffers=256MB", "-c", "max_connections=500"]
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./init-database.sh:/docker-entrypoint-initdb.d/init-database.sh
    environment:
      - POSTGRES_PASSWORD=kataku 
    ports:
      - 5455:5432
    env_file:
      - .env
    expose:
      - 5455
    networks:
      - app-network-ndakisa

  adminer:
    image: adminer
    container_name: ndakisa-adminer
    restart: always
    ports:
      - 8084:8080
    networks:
      - app-network-ndakisa

volumes:
  postgres:
    driver: local 

networks:
  app-network-ndakisa:
    driver: bridge

# docker system prune
# docker rmi -f ndakisa-api  // Supprimer une image
# docker rm -f <Container ID> // 260fb7520a70
# docker compose build ndakisa
# docker compose up --build -d
# docker compose up --rebuild -d
